<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>795661aa-f9d6-46fa-93cd-bc21f85cce07</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TmsOmsIntegration.Application\TmsOmsIntegration.Application.csproj" />
    <ProjectReference Include="..\TmsOmsIntegration.Infrastructure\TmsOmsIntegration.Infrastructure.csproj" />
  </ItemGroup>

</Project>
